Add nested folders
Appyo-Poste/PosteBackend pull request #38
Opened 2024-02-12 04:25 UTC by mccodav1

2024-02-12 17:06 UTC, atreichl approved these changes, later dismissed
This looks good to me overall. The changes make sense and as far as I can test work. One possible issue I found was that you can't delete a user from the admin site at least. If you try you get an error saying that you can't delete the users root folder. 
![image](https://github.com/Appyo-Poste/PosteBackend/assets/127570704/4e77aff5-2f57-415f-ac64-fc9e5808794a)
 
![image](https://github.com/Appyo-Poste/PosteBackend/assets/127570704/5325f5cb-75f2-40c2-a62f-f26480c9cd00)

2024-02-13 01:25 UTC, atreichl requested changes
Not allowing the deletion of root folder is causing issues with deletion of users.

2024-02-17 23:09 UTC, atreichl approved these changes

2024-02-20 10:35 UTC, mccodav1 commented
> Not allowing the deletion of root folder is causing issues with deletion of users.

Fixed this issue by moving folder deletion logic. It should now allow User deletion and delete their root folders, while still preventing root folder deletion while the user exists.

2024-02-20 10:35 UTC, merged